variables:
  - name: 'vmImageName'
    value: 'ubuntu-latest'
  - name: 'serviceConnectionName'
    value: 'Azure'
  - name: 'project'
    value: 'tegernseer'

resources:
  pipelines:
    - pipeline: ci
      source: 'Tegernseer CI'
      trigger: true

pool:
  vmImage: $(vmImageName)

pr:
  branches:
    include: ['dev']
  paths:
    include:
      - 'src/*'
      - 'infrastructure/*'
      - 'tests/*'

trigger: none

stages:
  - stage: Integration
    displayName: Integration
    jobs:
      - template: ./templates/backend-stage.yml
        parameters:
          VmImage: $(vmImageName)
          Environment: Integration
          StageShort: int
          ServiceConnectionName: $(serviceConnectionName)
          ProjectName: $(project)
          DeployBicep: false
          Sites:
            - name: 'api-ro-tegernseer'
              package: 'Services.CoreApi.zip'
              linux: true
              net: 6
            - name: 'api-ro-tegernseer-cleanup'
              package: 'Services.CleanupApi.zip'
              linux: true
              net: 6
            - name: 'api-ro-tegernseer-import'
              package: 'Services.ImportApi.zip'
              linux: true
              net: 6
            - name: 'api-ro-tegernseer-notification'
              package: 'Services.NotificationApi.zip'
              linux: true
              net: 6
            - name: 'ui-ro-tegernseer'
              package: 'Ui.Web.zip'
              linux: true
              net: 6
  - stage: Test
    displayName: Test
    jobs:
      - template: ./templates/backend-stage.yml
        parameters:
          VmImage: $(vmImageName)
          Environment: Test
          StageShort: test
          ServiceConnectionName: $(serviceConnectionName)
          ProjectName: $(project)
          DeployBicep: false
          Sites:
            - name: 'api-ro-tegernseer'
              package: 'Services.CoreApi.zip'
              linux: true
              net: 6
            - name: 'api-ro-tegernseer-cleanup'
              package: 'Services.CleanupApi.zip'
              linux: true
              net: 6
            - name: 'api-ro-tegernseer-import'
              package: 'Services.ImportApi.zip'
              linux: true
              net: 6
            - name: 'api-ro-tegernseer-notification'
              package: 'Services.NotificationApi.zip'
              linux: true
              net: 6
            - name: 'ui-ro-tegernseer'
              package: 'Ui.Web.zip'
              linux: true
              net: 6
  - stage: Production
    displayName: Production
    jobs:
      - template: ./templates/backend-stage.yml
        parameters:
          VmImage: $(vmImageName)
          Environment: Production
          StageShort: prod
          ServiceConnectionName: $(serviceConnectionName)
          ProjectName: $(project)
          DeployBicep: false
          Sites:
            - name: 'api-ro-tegernseer'
              package: 'Services.CoreApi.zip'
              linux: true
              net: 6
            - name: 'api-ro-tegernseer-cleanup'
              package: 'Services.CleanupApi.zip'
              linux: true
              net: 6
            - name: 'api-ro-tegernseer-import'
              package: 'Services.ImportApi.zip'
              linux: true
              net: 6
            - name: 'api-ro-tegernseer-notification'
              package: 'Services.NotificationApi.zip'
              linux: true
              net: 6
            - name: 'ui-ro-tegernseer'
              package: 'Ui.Web.zip'
              linux: true
              net: 6
